image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run build
    - mkdir public
    - mv index.html public/
    - mv dist/ public/dist/
  artifacts:
    paths:
      - public
  only:
    - master
